### ISSUE TITLE
GUI not able to process sparse_model.pp file (generated from meshlab)

### ISSUE THREAD

**Issue by avasalya** [rohanpsingh/RapidPoseLabels#8]
Hi @rohanpsingh 

Thank you for the great work, loving it,

so far I have followed all the instructions and able to generated **sparse_model.txt** and **.npz** files when using **"create new model"** option from the GUI.

however when I try to use the option "**use existing model**" and load meshlab generated **sparse_model.pp** file, I am able to reassign keypoints (7 in my case) and visualize point cloud -- so far everything works fine.

but when I click **_compute_** I get the following error

`File "/home/ash/anaconda3/envs/rpl/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/ash/RapidPoseLabels/src/app/gui.py", line 217, in btn_func_compute
    res, obj = self.process.compute(True)
  File "/home/ash/RapidPoseLabels/src/app/process.py", line 144, in compute
    object_model = SparseModel().reader(self.sparse_model_file)
  File "/home/ash/RapidPoseLabels/src/utils/sparse_model.py", line 46, in reader
    dict_ = {name:float(val.strip('"')) for item in line for name,val in [item.strip('/>').split('=')]}
  File "/home/ash/RapidPoseLabels/src/utils/sparse_model.py", line 46, in <dictcomp>
    dict_ = {name:float(val.strip('"')) for item in line for name,val in [item.strip('/>').split('=')]}
ValueError: could not convert string to float: 'new'
`

this is the content of file **sparse_model.pp** generated using meshlab
```
<!DOCTYPE PickedPoints>
<PickedPoints>
 <DocumentData>
  <DateTime time="11:07:59" date="2020-10-27"/>
  <User name="ash"/>
  <DataFileName name="dense.ply"/>
  <templateName name="new Template"/>
 </DocumentData>
 <point x="-0.0167179" y="0.0209239" z="0.0357646" active="1" name="new point1"/>
 <point x="0.00372273" y="-0.00988487" z="0.0208798" active="1" name="new point2"/>
 <point x="0.0315655" y="-0.0385553" z="0.000173726" active="1" name="new point3"/>
 <point x="-0.00984707" y="-0.0384084" z="-0.0119959" active="1" name="new point4"/>
 <point x="-0.0496232" y="-0.0395572" z="-0.0182423" active="1" name="new point5"/>
 <point x="-0.0343752" y="-0.0097153" z="0.00932476" active="1" name="new point6"/>
 <point x="-0.0130576" y="-0.0125543" z="0.0157916" active="1" name="new point7"/>
</PickedPoints>
```

I would appreciate any help you could provide

thanks

**Comment by rohanpsingh** [comment]
Can you share the *.pp file too?

**Comment by rohanpsingh** [comment]
Sorry there was a bug in SparseModel reader.
#9 should fix it
Please pull master branch and try again

**Comment by avasalya** [comment]
thanks its working now, however one can also just rename the point name from `"new point1"` to just `"1", "2",` etc
its a short fix but would work as well
